language: ruby
rvm:
- 2.4.0
bundler_args: --jobs=2
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
script:
  - bundle exec rake db:setup
  - bundle exec rake spec
cache: bundler
services:
  - postgresql
